import dotenv from "dotenv";

dotenv.config();

const {
  PORT,
  DB_HOST,
  DB_PORT,
  DB_USERNAME,
  DB_PASSWORD,
  DB_NAME,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  VERIFICATION_TOKEN_SECRET,
  MAIN_DOMAIN,
  RABBIT_MQ_URL,
  RABBIT_MQ_EXCHANGE,
  AUTH_QUEUE,
  PREFETCH,
} = process.env;

export const env = {
  PORT,
  DB_HOST,
  DB_PORT,
  DB_USERNAME,
  DB_PASSWORD,
  DB_NAME,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  VERIFICATION_TOKEN_SECRET,
  MAIN_DOMAIN,
  RABBIT_MQ_URL,
  RABBIT_MQ_EXCHANGE,
  AUTH_QUEUE,
  PREFETCH,
};
