import dotenv from "dotenv";

dotenv.config();

const {
  ACCESS_TOKEN_SECRET,
  RABBIT_MQ_URL,
  RABBIT_MQ_EXCHANGE,
  EMAIL_QUEUE,
  PREFETCH,
  SMTP_USER,
  SMTP_PASS,
  EMAIL_FROM,
  AUTH_SERVICE_URL,
} = process.env;

export const env = {
  ACCESS_TOKEN_SECRET,
  RABBIT_MQ_URL,
  RABBIT_MQ_EXCHANGE,
  EMAIL_QUEUE,
  PREFETCH,
  SMTP_USER,
  SMTP_PASS,
  EMAIL_FROM,
  AUTH_SERVICE_URL,
};
